[package]
name = "chillable/mew"
description = "A simple game framework"
version = "2.0.8"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
